### PR TITLE
Fibonacci and Factorial

### PR DESCRIPTION
**Pull request by Gulynim**
Fibonacci and Factorial were created! Please check if it looks ok!

### CODE REVIEW

**Comment by Nadira777** [comment]
Great!

**Comment by Barno74** [comment]
Thank you so much.

**Review by Nadira777 — APPROVED** [review]
Great!

**Review by tilbearslan — APPROVED** [review]
Looks good!

**Review by nurgul3374 — COMMENTED** [review]
looks good

**Review by Barno74 — APPROVED** [review]
Looks good

**Review by nurgul3374 — COMMENTED** [review]
ok

**Pull request merged**
